# -*- coding: utf-8 -*-
"""Temprature_Converter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C1BbRDtFrJVEcT4uLPQH6bUHTAJbZySa
"""
# Convert Celcius to Fahrenheit
def celcius_to_fahrenheit(celcius):
    return (celcius* 9/5) + 32
# Converte Fahrenheit to Celcius
def fahrenheit_to_celcius(fahrenheit):
    return (fahrenheit - 32) * 5/9
# Main function to run converter
def temprature_converter():
    print('Tempratue converter!')
    print('1. Celcius to Fahrenheit')
    print('2. Fahrenheit to celcius')

    choice=input('Chose conversion 1 or 2: ')

    if choice == '1':
        celcius=float(input('Enter Tempratue Celcius: '))
        fahrenheit=celcius_to_fahrenheit(celcius)
        print(f'{celcius} C is equal to {fahrenheit:.2f} F ')

    elif choice == '2':
        farenheit=float(input('Enter Tempratue in Fahrenheit: '))
        celcius=farenheit_to_celcius(farenheit)
        print(f'{farenheit} F is equal to {celcius:.2f} C ')
    else:
        'invalid choice please enter choice 1 or 2'
# Run Converter
temprature_converter()
