# -*- coding: utf-8 -*-
"""Temprature_Converter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C1BbRDtFrJVEcT4uLPQH6bUHTAJbZySa
"""

def celcius_to_farenheit(celcius):
    return (celcius* 9/5) + 32

def farenheit_to_celcius(farenheit):
    return (farenheit - 32) * 5/9

def temprature_converter():
    print('Tempratue converter!')
    print('1. Celcius to Farenheit')
    print('2. Frenheit to celcius')

    choice=input('Chose conversion 1 or 2: ')

    if choice == '1':
        celcius=float(input('Enter Tempratue Celcius: '))
        farenheit=celcius_to_farenheit(celcius)
        print(f'{celcius} C is equal to {farenheit:.2f} F ')

    elif choice == '2':
        farenheit=float(input('Enter Tempratue in Farenheit: '))
        celcius=farenheit_to_celcius(farenheit)
        print(f'{farenheit} F is equal to {celcius:.2f} C ')
    else:
        'invalid choice please enter choice 1 or 2'

temprature_converter()